language: java
jdk:
- oraclejdk8
before_install: wget http://download.jetbrains.com/mps/33/MPS-3.3.5.zip
install: unzip MPS-3.3.5.zip
script: ant -Dmps_home=./MPS\ 3.3 clean generate assemble
deploy:
  provider: releases
  api_key:
    secure: 75bffff38dd337f62f0e6f70859425c8b6cdcc15
  file: "build/artifacts/com.dslfoundry.plaintextgen/com.dslfoundry.plaintextgen.zip"
  skip_cleanup: true
  on:
    repo: DSLFoundry/mps-plaintextgen
    tags: true
